name: kGiftMechanic
version: '1.0'
main: vv0ta3fa9.plugin.kGiftMechanic.MainClassManager
api-version: '1.16'
load: STARTUP
authors: [ vv0t3afa9 ]
website: t.me/kapybarkaaa

commands:
  kgm:
    description: Команда для получения награды за подарки
    usage: /kgm take
    aliases: [kgiftmechanic]
